### ISSUE TITLE
Publish on Twinpack

### ISSUE THREAD

**Issue by beslst** [TcHaxx/rplc#1]
Hi! We implemented a package manager for TwinCAT, similarly to nuget.

https://github.com/zeugwerk/twinpack

It is integrated in TcXAEShell and Visual Studio and also offers a simple command line interface for downloading and uploading packages on CI environments. Ultimately we want to make DevOps more accessible in the PLC world and having an open source package manager is our first step towards this goal.

Would you upload rplc to Twinpack to facility the installation of it for TwinCAT users?

**Comment by densogiaichned** [comment]
Hi @iadonkey,

i've tried to implement your [Zeugwerk/zkbuild-action](https://github.com/Zeugwerk/zkbuild-action).
However, the build fails, see https://github.com/TcHaxx/rplc/actions/runs/7518303609/job/20465486609.
What am I missing here?

Regards

**Comment by beslst** [comment]
Looks like a bug, maybe because you use variants. I will look into this next week and provide a fix, thanks for the report about the defect!! I will come back to you when it’s fixed

For publishing on Twinpack we developed “Twinpack Registry” in the mean time. This automates publishing on the package manager and requires no manual action on your side. The only prerequisite to make it work is that you use GitHub Releases and the .library file is an asset of the release, see https://github.com/Zeugwerk/Twinpack-Registry 
Once your repository is in the “repositories.txt” file, your repo is automatically scanned for new releases once a day (see https://github.com/Zeugwerk/Twinpack/actions/runs/7512704345/job/20453671496 )

**Comment by beslst** [comment]
There was a bug in zkbuild when having > 2 PLC in the TwinCAT solution, but only having 1 PLC in the config.json, which is fixed now.
I also had to add TcUnit to the dependencies (see Pull Request) listed in the config.json, because it seems that you have the variant UNITTEST committed.

While I really like using Variants to exclude Tests from the build, we don't support this with zkbuild at the moment. At the moment we only support two ways to implement tests, which are listed [here](https://github.com/Zeugwerk/zkbuild-action#unittests). zkbuild will automatically remove all tests for the normal build when using Variant 2.
I'll add a feature request to support your way of testing as well, but this will take a while ...

**Comment by densogiaichned** [comment]
Hey @iadonkey,

not sure why it picked up `v0.2.3.0` instead of `v0.3.0.0`, see logs of [last run](https://github.com/TcHaxx/rplc/actions/runs/7670280473/job/20906082746):
[4_Build rplc.txt](https://github.com/TcHaxx/rplc/files/14067010/4_Build.rplc.txt)

Regards

**Comment by beslst** [comment]
hm, I am not sure to be honest. I tried to replay the build on the CI server and then it correctly picked up v0.3.0. Maybe the tags were pushed after the commit? I'll try to reproduce it

**Comment by densogiaichned** [comment]
Yapp, sorry my fault, didn't think about the tags...
Nevermind!

**Comment by beslst** [comment]
You can always just start the build again. zkbuild automatically sets the tag version in the plcproj before building.

**Comment by beslst** [comment]
i think we can close the issue? thanks for putting the library on twinpack!
