### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by Rednas83** [TcHaxx/rplc#3]
Currently working on a project which requires communication between tc3 and a nuxt/vue/typescript application.

Before getting started I have a couple of questions.

Is it just for PLC/PLC communication or can it also be used for different applications?

Does it work with grpc or with trpc? 

Could it for example be used in combination with https://trpc-nuxt.vercel.app/get-started/usage/simple?

Does it require a special license like opc-ua?

**Comment by densogiaichned** [comment]
Hello,

it's not only for PLCs, can also be used for other applications.
However, you'll need some sort of middleware, hence a ADS server which provides those RPC methods, e.g. [Example TF6000](https://github.com/Beckhoff/TF6000_ADS_DOTNET_V5_Samples/blob/main/Sources/ServerSamples/AdsSymbolicServerSample/AdsSymbolicServer.cs).
gRPC or trpc will not work directly, again a middleware is needed.
If you'll have a one, it might be better to call PLC functions, instead the other way around (PLC --> middleware).
In this case see [TcAdsClient.InvokeRpcMethod](https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_adsnetref/7313454219.html)

A special license is not needed, it works with a regular PLC license - TC1200.

Regards
